// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuM9kxOvl2UujQZaU1AJJ5WCArINrxkE',
    appId: '1:589003228951:android:c23918b494eaf4fa641952',
    messagingSenderId: '589003228951',
    projectId: 'gossip-e7212',
    storageBucket: 'gossip-e7212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdNqGyP5xduM99Vmu1pzeqwQyUT6uAREc',
    appId: '1:589003228951:ios:baff535ef8b1871a641952',
    messagingSenderId: '589003228951',
    projectId: 'gossip-e7212',
    storageBucket: 'gossip-e7212.appspot.com',
    androidClientId: '589003228951-4u5vhr2ak0rg0eqcpmoqpns5mhs70jgg.apps.googleusercontent.com',
    iosClientId: '589003228951-of47t48hlib35ukqojiq68vicf9vkao9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipFlutter',
  );
}
